model:
  _target_: src.models.i2i.mtdtnet.Mtdtnet
  architecture:
    encoder:
      _target_: src.models.i2i.mtdtnet.Encoder
      channels: 3

    generator:
      _target_: src.models.i2i.mtdtnet.Generator

    st_encoder:
      _target_: src.models.i2i.mtdtnet.Style_Encoder
      channels: 3

    discrminator:
      _target_: src.models.i2i.mtdtnet.Multi_Head_Discriminator
      num_domains: 2
      channels: 3

    domain_transfer:
      _target_: src.models.i2i.mtdtnet.Domain_Transfer
      targets: ["${target_data}"]

    label_embed:
      _target_: src.models.i2i.mtdtnet.Label_Embed

  loss:
    type: [Gan_g, Direct_recon, Indirect_recon, Consis, Style, Gan_d] #losses.py에 있는 함수이름 작성
    weight: [1.0, 1.0, 0.1, 1.0, 1e3, 1.0]
    
  datasets: ["${source_data}", "${target_data}"]
  pretrained_mtdtnet: #pretrained/mtdtnet/mtdtnet.pth

generator_optimizer:
  type: Adam
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 1e-5

discriminator_optimizer:
  type: Adam
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 1e-5
