defaults:
  - _self_
  - log_dir: default.yaml
  - logger: Tensorboard.yaml
  - seg_model: Segformer.yaml
  - i2i_model: Mtdtnet.yaml
  - label_filtering: BARS.yaml
  - source_dataset: GTA5.yaml         # have to modify with source_data below
  - target_dataset: Cityscapes.yaml   # have to modify with target_data below
  - data_loader: default.yaml
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# directory
work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/datasets/

# expriment information
ex: "test"
description: "test"

# training
#seg_pretrained: "do not delete/mtdt-net seg training iter experminet/13-58-13_uda G->C mtdt-net without bars/Segformer.pth"
seg_pretrained: #"pretrained/segformer/segformer_mitb5_46.75_single.pth"
i2i_pretrained: null
seg_start_iter: 1 # in training code
pl_start_iter: 500 
max_iteration: 1000000
eval_interval: 50
tensor_interval: 10

seg_loss_weight: [0.9, 0.1] # source2target , target
seg_lr: 6e-5

# dataset
source_data: GTA5         # have to modify with source_dataset in defaults
target_data: Cityscapes   # have to modify with target_dataset in defaults
img_size: [512, 1024]
class_num: 19

# environment variable
rand_seed: 3621