defaults:
  - _self_
  - log_dir: default.yaml
  - logger: Tensorboard.yaml
  - seg_model: Segformer.yaml
  - source_dataset: GTA5.yaml
  - target_dataset: Cityscapes.yaml
  - data_loader: default.yaml
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# directory
work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/datasets/

# expriment information
ex: "test"
description: "test"

# training
seg_pretrained: "pretrained/segformer/segformer_mitb5_46.92.pth"
max_iteration: 1000000
eval_interval: 500
tensor_interval: 100

# dataset
img_size: [512, 1024]
class_num: 19

# environment variable
rand_seed: 3621
