# @package _global_

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${ex}
  sweep:
    dir: logs/experiments/multiruns/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}